import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

// The landing page has no bundler, so it carries a COPY of the icons as an inline SVG sprite.
// A copy drifts: fix a glyph in the app and the site keeps the old one forever, and nobody
// notices because both render fine. These tests make drift fail CI instead of ageing quietly.

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const iconSrc = readFileSync(join(root, "src/Icon.tsx"), "utf8");
const sprite = readFileSync(join(root, "docs/_icons.svg"), "utf8");
// docs/index.html is GENERATED by scripts/gen-landing.mjs and is gitignored — reading it made
// this suite fail in CI with ENOENT while passing locally, because only a local build has it.
// The tracked sources are the template and the generator, and between them they hold every icon.
const page =
  readFileSync(join(root, "docs/_template.html"), "utf8") +
  readFileSync(join(root, "scripts/gen-landing.mjs"), "utf8");

const appGlyphs = [
  ...(iconSrc.split("const P: Record<IconName, React.ReactNode> = {")[1]?.split("\n};")[0] ?? "")
    .matchAll(/^ {2}([a-z][\w]*): /gm),
].map((m) => m[1]);

describe("landing page icon sprite", () => {
  it("finds the glyphs (guard: worthless if either parse breaks)", () => {
    expect(appGlyphs.length).toBeGreaterThan(40);
    expect(sprite).toContain("<symbol");
  });

  it("has a symbol for every glyph the app defines", () => {
    const missing = appGlyphs.filter((g) => !sprite.includes(`id="i-${g}"`));
    expect(missing, `regenerate: node scripts/build-icon-sprite.mjs — missing ${missing.join(", ")}`).toEqual([]);
  });

  it("every icon the page USES exists in the sprite", () => {
    // A typo'd <use href="#i-brian"> renders as nothing at all — an invisible hole, no error.
    const used = [...page.matchAll(/href="#i-([\w-]+)"/g)].map((m) => m[1]);
    expect(used.length).toBeGreaterThan(10);
    const broken = [...new Set(used)].filter((u) => !page.includes(`id="i-${u}"`));
    expect(broken, `these would render as empty space: ${broken.join(", ")}`).toEqual([]);
  });

  it("the page ships no emoji doing icon duty", () => {
    const emoji = page.match(/[\u{1F300}-\u{1FAFF}]/gu) ?? [];
    expect(emoji, `emoji left on the landing page: ${[...new Set(emoji)].join(" ")}`).toEqual([]);
  });

  it("stays self-contained — no external icon requests", () => {
    // The sprite is inlined deliberately: one file, works offline, nothing to 404 later.
    expect(page).toContain("<symbol");
    expect(page).not.toMatch(/<use[^>]+href="https?:/);
  });
});

describe("landing page claims", () => {
  // The numbers are NOT hardcoded — the template carries {{TOOLS}}/{{SKILLS}}/{{AGENTS}}
  // placeholders and gen-landing.mjs fills them from the same counter that writes stats.json.
  // So the honest thing to test is that the wiring exists, not that some digits match: if the
  // placeholders survive, the published page cannot state a stale number.
  const template = readFileSync(join(root, "docs/_template.html"), "utf8");
  const gen = readFileSync(join(root, "scripts/gen-landing.mjs"), "utf8");

  it("keeps the counts as placeholders, never hardcoded digits", () => {
    for (const ph of ["{{TOOLS}}", "{{SKILLS}}", "{{AGENTS}}", "{{BRAINS}}"]) {
      expect(template, `${ph} missing — a hardcoded number would go stale silently`).toContain(ph);
    }
  });

  it("the generator fills them from the real counter", () => {
    for (const ph of ["TOOLS", "SKILLS", "AGENTS", "BRAINS"]) {
      expect(gen, `generator never substitutes {{${ph}}}`).toContain(ph);
    }
  });
});
