// SAM · PLATFORM CAPABILITY MATRIX generator.
// Walks every tool's source, detects OS gating (a `!IS_MAC` / `OS !== "mac"` guard or a
// notSupported() early-return), and emits docs/PLATFORMS.md: which tools are universal vs macOS-only,
// and confirms macOS-only tools DEGRADE cleanly (they return a message, never crash). Run: `npm run platforms`.
import { TOOLS } from "../server/tools.ts";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = readFileSync(join(root, "server/tools.ts"), "utf8");

// Slice each tool's block: from `{ name: "X"` to the next `{ name: "` (or EOF).
const blocks = new Map<string, string>();
const re = /\{\s*name:\s*"([a-z0-9_]+)"/g;
const marks: { name: string; idx: number }[] = [];
for (let m = re.exec(src); m; m = re.exec(src)) marks.push({ name: m[1], idx: m.index });
for (let i = 0; i < marks.length; i++) blocks.set(marks[i].name, src.slice(marks[i].idx, marks[i + 1]?.idx ?? src.length));

const MAC_GATE = /!IS_MAC|OS\s*!==\s*"mac"|notSupported\(|needs macOS|only (works on|on) macOS/;
const macOnly: string[] = [], universal: string[] = [];
for (const t of TOOLS) {
  const b = blocks.get(t.name) || "";
  (MAC_GATE.test(b) ? macOnly : universal).push(t.name);
}
// Every macOS-only tool must have a clean early-return (message), not just an unguarded mac command.
const ungatedRisk = macOnly.filter((n) => !/return\s+(notSupported\(|["'`])/.test(blocks.get(n) || ""));

const md = `# Platform capability matrix

_Auto-generated by \`npm run platforms\` — do not edit by hand._

SAM runs on **macOS, Windows, and Linux**. ${universal.length} of ${TOOLS.length} tools are **universal**
(Node-native or OS-branched — they work identically everywhere). ${macOnly.length} are **macOS-only**
(they drive Apple-specific system features); on Windows/Linux they return a clean "only on macOS"
message and **never crash or fail silently**.

| | Count | Windows | Linux | macOS |
|---|---:|:---:|:---:|:---:|
| **Universal tools** | ${universal.length} | ✅ | ✅ | ✅ |
| **macOS-only tools** | ${macOnly.length} | ⚪ clean message | ⚪ clean message | ✅ |

## macOS-only tools (${macOnly.length})
These use Apple-specific features (AppleScript, \`say\`, Shortcuts, \`diskutil\`, \`pmset\`, Wi-Fi, iMessage,
FaceTime, Apple Maps). On other platforms they return a graceful "not available" message.

${macOnly.sort().map((n) => `\`${n}\``).join(" · ")}

## Universal tools (${universal.length})
Everything else — file ops, web/search/fetch, DNS, git/GitHub, memory, notebooks, media generation,
calendar, clipboard, screenshots, lock-screen, process control, and more — works on all three OSes.

${ungatedRisk.length === 0
  ? "✅ **Every macOS-only tool degrades cleanly** (verified: each has a message early-return, not an unguarded Apple command)."
  : `⚠️ **These macOS-only tools may not degrade cleanly — fix them:** ${ungatedRisk.join(", ")}`}
`;

writeFileSync(join(root, "docs/PLATFORMS.md"), md);
console.log(`✓ docs/PLATFORMS.md → ${universal.length} universal · ${macOnly.length} macOS-only · ${ungatedRisk.length} ungated-risk`);
if (ungatedRisk.length) process.exit(1);
